on: 
  push:
jobs: 
  mail_on_push: 
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: 'Commit detected in ${{ github.repository }}'
          body:
            Hello,
            Please be noted, a single commit created by ${{github.event.pusher.name}}
          to: andrei.tupitsin@gmail.com
          from: ${{ secrets.MAIL_USERNAME }}
